# Generated by Django 5.2.3 on 2025-06-16 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu_name",
                    models.CharField(max_length=100, verbose_name="Название меню"),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Заголовок пункта"),
                ),
                (
                    "url",
                    models.CharField(blank=True, max_length=200, verbose_name="URL"),
                ),
                (
                    "named_url",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Named URL"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="menu.menuitem",
                        verbose_name="Родитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
                "ordering": ["order"],
            },
        ),
    ]
